### ISSUE TITLE
Tweak-XL will corrupt game files, making cyperpunk 2077 unstartable, until you repair the files via gog luncher.

### ISSUE THREAD

**Issue by njalooo** [psiberx/cp2077-tweak-xl#1]
So i've installed Mod Manager 2, and have only Cyber Engine Tweaks, RED4ext and redscript above Tweak-XL in the load order. When i try to start Cyberpunk, it will give a crash message with the recommendation to repair your files. Without Tweak-XL but the others there is no issue. When repairing files, the GOG Louncher will download 44MB of files, i couldn't get more detail sadly...

**Comment by psiberx** [comment]
The message means RED4ext is not installed or working. You have to follow RED4ext instructions to fix it.
