### ISSUE TITLE
Invalid value error..

### ISSUE THREAD

**Issue by regtoaccess** [psiberx/cp2077-tweak-xl#3]
If I append 'Reinforced Tendons' description to 'Lynx Paws' I get an error in TweakXL log.

Method one:
```
Items.CatPaws:
  localizedDescription:
    - !append LocKey#40876
```
`[error] Items.CatPaws.localizedDescription: Invalid value, expected gamedataLocKeyWrapper.`

Method two:
```
Items.CatPaws_inline0:
  UIData:
    - !append Items.BoostedTendonsRare_inline2
```
`[error] Items.CatPaws_inline0.UIData: Invalid value, expected TweakDBID.`

But despite the error, the code passes through and the game appends the description as intended (in both cases). Is there a better way to achieve this, or is it just a linter issue?

EDIT:
If I replace the original LocKey (without - !append) I don't get an error.

ex:
`Items.CatPaws.localizedDescription: LocKey#40876`

**Comment by psiberx** [comment]
This is correct behavior. `localizedDescription` and `UIData` are not arrays.
