### ISSUE TITLE
Game crash Tweak XL

### ISSUE THREAD

**Issue by Skibblerab** [psiberx/cp2077-tweak-xl#4]

**Comment by Skibblerab** [comment]
Tweak XL is not functional for me. I've tried install Vortex, Github, newest- older versions, have tried disabling redmod, have tried on steam and used separate file (Backup file location). I've even tried putting files into other locations(shot in the dark), but nothing seem to work except disabling the mod. Tips?

**Comment by dragonzkiller** [comment]
This is not an issue. The game was updated again, and requires another update. Please be patient for psi to update the mods. You may follow updates on the cyberpunk modding discord.

**Comment by gir489returns** [comment]
> This is not an issue.
> requires another update.

Pick one, idiot.

**Comment by mm-psetest** [comment]
bated breath
