### ISSUE TITLE
Incorrectly uploaded release file for TweakXL 1.5.0

### ISSUE THREAD

**Issue by NetroScript** [psiberx/cp2077-tweak-xl#8]
The `TweakXL.dll` file which is currently uploaded in the [TweakXL-1.5.0.zip](https://github.com/psiberx/cp2077-tweak-xl/releases/download/v1.5.0/TweakXL-1.5.0.zip) still has `1.4.4` as version number.
Same thing for the version 1.5.0 on NexusMods. 

Taking a look at your most recent changes however in https://github.com/psiberx/cp2077-tweak-xl/commit/3ef81ff7070412cabdabf292614b186c0e8dae11 you updated these values. 

Compiling the DLL locally also results in a `.dll` file with version number `1.5.0`.

Because of this I assume you did a mistake while uploading the files and selected the wrong compiled version.

**Comment by psiberx** [comment]
If it was 1.4.4 it wouldn't work on patch 2.02. The process is fully automated including file name. I'm not sure why version info in for DLL is old, but it's 1.5.0.
