### ISSUE TITLE
TweakXL causes crash

### ISSUE THREAD

**Issue by teleprint-me** [psiberx/cp2077-tweak-xl#9]
![Screenshot from 2023-11-19 21-22-03](https://github.com/psiberx/cp2077-tweak-xl/assets/77757836/92991cfb-47c8-49d4-9d17-1137f10897b0)

I was able to narrow it down to `r6/scripts/TweakXL/TweakXL.reds` which looks like it's a concatenated variation of the source files in `cp2077-tweak-xl/support/redscript`.

If I remove `TweakXL.reds`, then the game launches again.

I did take a look at the [wiki/Script-Extensions](https://github.com/psiberx/cp2077-tweak-xl/wiki/Script-Extensions), but I'm not that familiar with Red Script and don't have windows either (which makes it difficult to troubleshoot certain issues).

I thought I'd report. Hopefully it helps narrow down some crash related issues.

**Comment by psiberx** [comment]
Read FAQ on Nexus mod page.
